### ISSUE TITLE
Get hui/css to work

### ISSUE THREAD

**Issue by emilbayes** [hyperdivision/component#1]
Right now sheetify only looks for `require('sheetify')`: https://github.com/stackcss/sheetify/blob/7c446d208e670f12497fca9090e2ad310dd56a36/transform.js#L108-L117

But maybe we could make a PR to look at a list of aliases like they do on nanohtml: https://github.com/choojs/nanohtml/blob/bdd0efe65b1e9c26e04723588a19e629ca86fdde/lib/supported-views.js

**Comment by bcomnes** [comment]
I opened a PR here: https://github.com/stackcss/sheetify/pull/165

**Comment by bcomnes** [comment]
One more open source detail requested during the implementation of this: https://github.com/stackcss/sheetify/issues/166

**Comment by bcomnes** [comment]
I got publish access so this is no longer blocked.  Gettin this into my work queue.

**Comment by bcomnes** [comment]
Refactors to close this:

- https://github.com/hyperdivision/heimdall-desktop/pull/64
- https://github.com/hyperdivision/ui/pull/8
- https://github.com/hyperdivision/bfx-support-plugin/pull/15
